### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by mhsmith** [beeware/briefcase-linux-flatpak-template#1]
Since the first commit wasn't created via a PR, I'll post any review notes here.

**Comment by mhsmith** [comment]
https://github.com/beeware/briefcase-linux-flatpak-template/blob/86958cb98afc1a06b01d4a0a771b014d3f86a129/%7B%7B%20cookiecutter.formal_name%20%7D%7D/briefcase.toml#L1-L4

If this template doesn't use `support_path`, then the line should just be omitted rather than commented out.

**Comment by mhsmith** [comment]
@freakboy3742: It doesn't look like you're watching this repository, or is there some way to watch an entire GitHub organization?

**Comment by mhsmith** [comment]
It looks like the template doesn't currently use `app_packages_path` either. However, for Chaquopy I had the idea of making the template use briefcase.toml to give the path of the requirements.txt file (including filename). That way, the path doesn't need to be hard-coded in briefcase itself, and if it ever changes, only the template will need to be updated. 

In fact, if we use a different briefcase.toml variable, such as `app_requirements_path`, then the template can control whether to generate a requirements file or to run pip directly, so that doesn't need to be hardcoded in briefcase either.

I haven't implemented this yet, so if you want to do it for Flatpak then I'll reuse it. What I have in mind is merging the `install_app_dependencies` override in flatpak.py into the base class impementation in create.py, as follows:
* If `app_requirements_path` exists in briefcase.toml, then write a requirements file to that location.
* Otherwise, run pip to install to `app_packages_path`.

**Comment by freakboy3742** [comment]
That's a good idea - it means one less special case in the Flatpak backend, and it provides a clear flag that a template can use to opt-in to requirements generation rather than direct pip installation. I'll add this to my flatpak branch.

As for watching the repo; that was an oversight - I've adjusted my watch configuration (and done the same on a couple of other repos I've added recently).

**Comment by freakboy3742** [comment]
#2 addresses the template-related parts of this review.
